name: nextjs
type: service
from: node
fromVersionConstraint: "^1.0.0"
fromVersion: "1.0.3"
title: Node.js (Next.js)
labels:
- nextjs
- node

build:
  dockerfile: Dockerfile
  connect: true
  templates:
  - name: nextjs
    title: Next.js Boilerplate
    repo: https://github.com/wodby/nextjs-boilerplate
    branch: main
