name: nextjs
type: service
from: node
fromVersionConstraint: "^1.0.0"
fromVersion: "1.0.0"
icon: nextjs
title: Next.js
labels:
- nextjs

build:
  dockerfile: Dockerfile
  connect: true
  templates:
  - name: nextjs
    title: Next.js Boilerplate
    repo: https://github.com/wodby/nextjs-boilerplate
    branch: main
