name: nextjs
type: service
from: node
icon: nextjs
title: Next.js
labels:
- nextjs

build:
  dockerfile: Dockerfile
  connect: true
  templates:
  - name: nextjs
    title: Next.js Boilerplate
    repo: https://github.com/ixartz/Next-js-Boilerplate
    tag: ^v3
    pipeline: pipeline.yml
